export const DESCRIPTION =
  "Work with Azure DevOps work items, pull requests, and pipelines from the current profile";

export const TOP_LEVEL_HELP = [
  "ado-axi                                  # dashboard: your work items, PRs, recent runs",
  "ado-axi work-item list                   # open work items (WIQL under the hood)",
  "ado-axi work-item get <id>               # detail view [--comments] [--full]",
  'ado-axi work-item create --type Task --title "..."',
  "ado-axi work-item update <id> --state <state>",
  'ado-axi work-item comment <id> --body "..."',
  "ado-axi pr list                          # active pull requests [--repo <r>] [--status <s>]",
  "ado-axi pr get <id>                      # detail + reviewers [--threads] [--full]",
  'ado-axi pr create --repo <r> --source <branch> --title "..."',
  'ado-axi pr update <id> --title "..."     # draft/auto-complete/description updates',
  "ado-axi pr complete <id> [--squash]      # guarded merge; never bypasses policy",
  "ado-axi pr checks <id> | diff <id>       # bounded readiness/change summaries",
  "ado-axi pr reviewer list|add|remove <id>",
  "ado-axi pr approve <id>                  # [--vote approve|reject|wait-for-author|reset]",
  'ado-axi pr comment <id> --body "..."     # [--file <path> --line <n>] [--thread <id>]',
  "ado-axi pipeline list                    # pipeline definitions",
  "ado-axi pipeline runs [--pipeline <id>]  # recent runs [--result failed]",
  "ado-axi pipeline run --pipeline <id> --branch <branch>",
  "ado-axi pipeline logs <run-id>           # [--log <id>] [--tail N] [--full]",
  "ado-axi pipeline watch <run-id>          # [--interval 10] [--timeout 1800]",
  "ado-axi repo list                        # repositories [--name <filter>]",
  "ado-axi repo branches --repo <name>",
  "ado-axi ref list|create|delete --repo <name>",
  "ado-axi project list                     # projects, 30 most recently updated",
  "ado-axi api <path>                       # raw REST escape hatch for everything else",
  "ado-axi doctor                           # authentication check for every profile",
  "ado-axi config list | init | path        # profiles in ~/.ado-axi/config.json",
  "",
  "Profiles: --profile <name> selects a configured org/project/auth pair (also allowed before the command).",
  "Overrides: --org <org> --project <project> (or $ADO_AXI_ORG / $ADO_AXI_PROJECT).",
  "Auth per profile: az CLI login, or a PAT read from an env var.",
  "Output: TOON on stdout. --full disables truncation, --fields a,b limits list columns.",
].join("\n");

export const COMMAND_HELP: Record<string, string> = {
  "work-item": [
    "ado-axi work-item <list|get|create|update|comment>",
    "",
    "list    [--state open|all|<State>] [--type <type>] [--assigned-to @me|<name>]",
    "        [--iteration @current|<path>] [--area <path>] [--tag <tag>] [--search <text>]",
    '        [--query "<raw WIQL>"] [--limit 30] [--fields id,title,state]',
    "get     <id> [--comments] [--full]        # includes rev for --if-rev updates",
    'create  --type <type> --title "..." [--description "..."] [--assigned-to <user>]',
    '        [--area <path>] [--iteration <path>] [--parent <id>] [--tags "a; b"] [--set \'{"Field.Ref": value}\']',
    'update  <id> [--state <state>] [--title "..."] [--assigned-to <user>] [--area <path>]',
    '        [--iteration <path>] [--description "..."] [--tags "a; b"] [--reason <reason>] [--set \'{...}\']',
    "        # when --description is omitted, piped stdin is used",
    "        [--add-tags a,b] [--remove-tags c]  # mutate tags without rewriting the whole string",
    "        [--if-rev <n>]                      # compare-and-swap: fails if the item changed",
    'comment <id> --body "..."',
    "",
    "Examples:",
    "  ado-axi work-item list --assigned-to @me --state open",
    "  ado-axi work-item get 4211 --comments",
    '  ado-axi work-item update 4211 --state "In Progress"',
    "  ado-axi work-item update 4211 --assigned-to me@corp.com --add-tags agent-claimed --if-rev 7",
  ].join("\n"),
  pr: [
    "ado-axi pr <list|get|comments|create|update|complete|checks|diff|reviewer|approve|comment>",
    "",
    "list    [--repo <repo>] [--status active|completed|abandoned|all] [--creator @me|<name>]",
    "        [--reviewer @me|<name>] [--target <branch>] [--source <branch>] [--limit 30]",
    "get     <id> [--repo <repo>] [--threads] [--full]",
    "comments <id> [--repo <repo>] [--full]   # alias for `get <id> --threads`",
    'create  --repo <repo> --source <branch> [--target main] --title "..." [--description "..."]',
    "        [--reviewers a,b] [--draft] [--work-items 1,2]",
    'update  <id> [--title "..."] [--description "..."] [--draft true|false] [--auto-complete true|false]',
    "        # when no other update flag is supplied, piped stdin is used as the description",
    "complete <id> [--squash true|false] [--delete-source-branch true|false] [--repo <repo>]",
    "checks  <id> [--limit 10] [--full] [--repo <repo>]",
    "diff    <id> [--limit 20] [--full] [--repo <repo>]",
    "reviewer list <id> [--repo <repo>]",
    "reviewer add|remove <id> --reviewer <identity> [--required] [--repo <repo>]",
    "approve <id> [--vote approve|approve-with-suggestions|wait-for-author|reject|reset] [--repo <repo>]",
    'comment <id> --body "..." [--file <path> --line <n>] [--thread <id>] [--repo <repo>]',
    "",
    "Examples:",
    "  ado-axi pr list --reviewer @me",
    "  ado-axi pr get 812 --threads --full",
    "  ado-axi pr checks 812",
    "  ado-axi pr diff 812 --limit 50",
    "  ado-axi pr complete 812 --squash --delete-source-branch",
    "  ado-axi pr approve 812",
    "  MSYS_NO_PATHCONV=1 ado-axi pr comment 812 --file /src/File.cs --line 10 --body \"...\"  # Git Bash",
  ].join("\n"),
  pipeline: [
    "ado-axi pipeline <list|runs|run|logs|watch>",
    "",
    "list  [--name <filter>] [--limit 100]",
    "runs  [--pipeline <id>] [--branch <branch>] [--status <status>] [--result failed] [--limit 20]",
    "run   --pipeline <id> [--branch <branch>] [--variables '{\"k\":\"v\"}'] [--parameters '{\"k\":\"v\"}']",
    "logs  <run-id> [--log <log-id>] [--tail 120] [--full]",
    "watch <run-id> [--interval 10] [--timeout 1800]  # interval/timeout in seconds; failures exit 1",
    "",
    "Examples:",
    "  ado-axi pipeline runs --result failed --limit 5",
    "  ado-axi pipeline logs 98231 --tail 200",
    "  ado-axi pipeline watch 98231 --interval 10 --timeout 1800",
  ].join("\n"),
  repo: [
    "ado-axi repo <list|branches>",
    "",
    "list     [--name <filter>] [--limit 200]",
    "branches --repo <name> [--name <filter>] [--limit 50]",
  ].join("\n"),
  ref: [
    "ado-axi ref <list|create|delete>",
    "",
    "list   --repo <repo> [--name <prefix>] [--limit 50] [--full]",
    "create --repo <repo> --name <branch> (--source <branch> | --source-object-id <40-hex>)",
    "delete --repo <repo> --name <branch> [--old-object-id <40-hex>]",
    "",
    "Create never overwrites an existing ref. Delete reads the current object id and uses it as",
    "Azure DevOps' concurrency guard; --old-object-id adds an explicit caller-side guard.",
  ].join("\n"),
  project: ["ado-axi project list [--name <filter>] [--limit 30]"].join("\n"),
  api: [
    "ado-axi api [GET|POST|PATCH|PUT|DELETE] <path> [--body '<json>' | --body -] [--query 'k=v&k2=v2']",
    "            [--api-version 7.1] [--host dev|vsrm|vssps|almsearch] [--no-project] [--raw] [--full]",
    "            [--content-type json|json-patch|merge-patch|text|<media type>]",
    "",
    "Raw Azure DevOps REST escape hatch. Paths are relative to",
    "https://dev.azure.com/<org>/<project>/ — pass --no-project for organization-level paths.",
    "Work item writes require --content-type json-patch.",
    "When --body is omitted and stdin is piped, stdin is sent as the raw request body (use --content-type as needed).",
    "",
    "Examples:",
    "  ado-axi api _apis/wiki/wikis",
    "  ado-axi api _apis/testplan/plans --query 'filterActivePlans=true'",
    "  ado-axi api POST _apis/search/codesearchresults --host almsearch --body '{\"searchText\":\"TODO\"}'",
    "  ado-axi api PATCH _apis/wit/workitems/4211 --content-type json-patch \\",
    "    --body '[{\"op\":\"test\",\"path\":\"/rev\",\"value\":7},{\"op\":\"add\",\"path\":\"/fields/System.State\",\"value\":\"Active\"}]'",
  ].join("\n"),
  doctor: [
    "ado-axi doctor [--config <path>]",
    "",
    "Verifies authentication for every configured profile and reports the identity",
    "each one resolves to. Exit code 0 even when a profile fails — read `status`.",
  ].join("\n"),
  config: [
    "ado-axi config <list|init|path>",
    "",
    "list  [--config <path>]",
    "init  --org <org> [--project <project>] [--name <profile>] [--auth az|pat] [--pat-env <VAR>] [--default]",
    "path  prints the resolved config file location",
    "",
    "Config lives in ~/.ado-axi/config.json (or ./ado-axi.config.json, or $ADO_AXI_CONFIG):",
    '  { "defaultProfile": "acme", "profiles": {',
    '      "acme": { "org": "acme", "project": "Platform", "auth": "az" },',
    '      "contoso": { "org": "contoso", "project": "Web", "auth": "pat", "patEnv": "ADO_CONTOSO_PAT" } } }',
  ].join("\n"),
};
